rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.6
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
    - rvm: jruby-head
      env: JRUBY_OPTS="--2.1"
env:
  global:
    - secure: EXFzGCqzWdi4KrYvtK2L+TFtpV42t8xQTdFCLIAQIxZJBH+0jNR0ylGE3MTEzNOa/LmWGFroqGY1vV6h/Mopb6FF+F2xeaq8zdzKICjaAnxJA4bELqjyMrKvSJHs4F1KxoJgh2JbNrhHVuL8F6ZUni5MfxOwd1gMHq2Tpgl13wsKOfv2zoI8cSULbMZr4Nqaxm6YBW+T5y+OMRmF4+NqxFBkQFwhOJm1e2O8St4dPD4SngFF/sETLxrDvc9eR7WKZ0PZvsMUjTjbXmp4eV3H/SSTCdwS70e3nEm4nFSNRLLgnP71AnXA1qANH6Q2gh0Tp6OiBlvzVbFxPekO5X4FQZkYcuIMeiDwXDcfVlo8gMAYi/eZfgzYM/9zkLIQS+Zs0nplr66Nt7AIcPIySwCtblnyQLiaMFli9C3BEwqthtzWmVQkhb5A9klLDtTHZIsULij1jF7nP8SdMXUOdLwElLaDVxdEvN8J1Sl3fDNdfvZh3Lw+VPMSfxy0LZ8o/rMh2A10SIAJAVQ+nzwDfg8hoJK8O7jS0ljoUoFJ8V6J6K7EeIJgCCaCZAjZpZ5Ca1SptFw8pVmy0SFAcxJ39Jw7o+BqXK8zhmd4NgNV5G7wkrQBm/dllz2Znm5jvooz42zOoi750cQk/PVB9aitwGnBTzYJwzO8ZxSyw8FKNZmZw8g=
    - secure: dijn5DM/+INaj33CGU4+4NSFYkTZN/lwWLQUw/whhd6e6sYJQKfwPSBuy1ArKUr0XDTYiM0n5pGQUvn02K9r4jV5Opir6MF6Nu3YA2Yrel9swAJP0XXvnqTgC24AVdAW2ZiX/Ms1E9PF3kxYWnNwyvo00uqKiSyIjEYbhdrW/SucE5LkJfqJpqMRB1EJVMVMJjaG+RvCtFkQ++6ATKON4/YFynrtXnQuRUHWTTRNuDcSY/o/Djoa06xACx6+beCa81L2lVOl8oqQ4RLjKpF0sgx74vtyjGB2gMND39LE/+GiZzmELsiHeGJl9nPOfKdMcWhhbHv5fCFGsWjhdlto6/NbbqWLMnJGU6mD/nzkh0J/sYG3dsWxDDbJ1JC5gEJhrHssj3oc1zM5pi1uwc0Do9SIFDZSOUlS00UTrE6IO1+L2yfkRmOC9U0KtqkHvoAZjQ7e9zQLix0tEHD3ujc7RE27nf77fSzH+HKC81xgZc4BBeFEOVWGmfnxu51wsorw9a3djI0/yBCgioEMp9JmNKz9xx7zQvWiU1YvubEmLZjAbH0tZxX/ex50De1Px2hzQc8iF9h9IX+/HmgPp74oOq7e/Hkis3F4oBkwmWFFe0MCKOOkogpxVwMQtCybGk2h5UcedS87OZjAKnDILUXrWEH4LjQFWB4bkoGN3rm+4QU=
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: rubygems
  api_key:
    secure: w1n8sOB2AWRd6Kdb3wUGC3dJKSHtwiyEyd5z9dhsdGS+5VCf9EKXOzvDygS6h9EkpI5AGim4redsGN47aM2fMqZUOcXF570Ez5cDEvy+xKNBDzlWR9cSv6MsA6g2Uom6CmWxni6l5APDANA10xLkj6MB1MDrOy929G39i/RYqi8omJE04jsV1gQEC8WUBNGEy7GLDYcHWOO7spfg9PKvGX0WJpyvrU409/KgtukKoshUQlNXUOU1uQNcmYwgVa1LaNg1Piy8VXf52UDuRhlFZy/9NXXJ+WAfV4vYwO6t/rqWrQg8J2eAT2vVvpaTXiAEB/eVpjNnTyMLw5MzcCgempd06ejIeC4wJBqiMeLtr5EvihND0kzbd47lBZJCylWi+kvfwITbqcpZxY+GhymNSR+Of6sMYG0oKMMwYYvBJRZ4inythICLID98ndlMFZWZzS20DZRoTQFme11fixYMhgF88O1QXpeC3hIMz2CfupyL7tw7yKCfFaKtOhmdGTY219+1y7+eCLBkcQFEC2AgRVRzOy/mZflYcw5gwqFwbOXjyjks8mcFgE/PQuANONm3KWawqqFEH5r0adZSvzmnvQaPiWs/60y+NmN4/JPjLi8DPL2VxT0iyZRLPF0T7TNdSdSmYkK0nML0hEistdN0oeBNUN5myIR2zcEBztaoM/0=
  on:
    tags: true
